### ISSUE TITLE
Connect account info of the 'reisgenootschap' to the 'reisgenootschap' person info cards

### ISSUE THREAD

**Issue by naomi-eliasar** [drikusroor/ohayo-goededagu#34]
- [x] Profile `bio` = Person card story
- [x] Profile `avatar` = Person card imgSrc
- [x] Profile `name` = Person card name
- [x] Profile `japaneseName` = Person card quote

Canceled (name now in `Profile` model):
- [ ] Account name = Person card name

**Comment by drikusroor** [comment]
In theory we could already go for a data-only solution: The account / profile models (it's a bit of a weird setup, I agree) contain all the information that we need to show those tiles. And we probably only need to query the accounts with the role of ADMINISTRATOR and/or MODERATOR (so that we don't show my mom on that page lulz)
